### ISSUE TITLE
updatehb

### ISSUE THREAD

**Issue by selfagency** [oh-my-fish/plugin-brew#4]
i created a fish script to update and cleanup homebrew and i was wondering if this is something you'd want to add to either this plugin or to plugin-osx:

```
function updatehb -d "Updates, cleans, and troubleshoots Homebrew"
  sudo chgrp -R admin /usr/local
  sudo chmod -R g+w /usr/local
  brew update
  brew upgrade
  brew prune
  brew cleanup
  brew doctor
end
```

**Comment by bpinto** [comment]
Dangerous brew commands. I hardly use them all, is it a daily function you use?

**Comment by selfagency** [comment]
near daily, yeah. i've never had any issues. if i need an older version of a given thing, i usually run it in a container. and i use rvm for ruby, composer for php, etc.. i guess it's more dangerous if you're actually building hombrew packages.

**Comment by bpinto** [comment]
I'm on the fence here, perhaps submit a PR and lets hear someone else's opinion?

**Comment by bobthecow** [comment]
I'm :-1: for including it. It's pretty destructive and seems unnecessary for most people.

**Comment by selfagency** [comment]
totally fine. i just don't understand why you guys consider it so destructive. could you elucidate so i understand what harm i may be causing myself?

**Comment by bobthecow** [comment]
if you have other software that lives in `/usr/local`, the chmod / chgrp stuff can break it in fairly difficult to fix ways. Sophos anti-virus is one example. Many things want specific file permissions, so setting group writable to everything under `/usr/local` can break those as well. `brew prune` and `cleanup` are necessarily destructive. They irrevocably remove user files from the filesystem, with no way to recover them. There's a reason homebrew doesn't run them automatically every time you do `brew upgrade`.

Running all these things yourself, if you know what you're doing, and if you don't have any special needs that dictate otherwise, isn't a bad thing and isn't dangerous. Packaging them all up in a somewhat ambiguously named function _is_ dangerous :)

**Comment by selfagency** [comment]
hm. are you sure about that? when you run brew doctor, if /usr/local doesn't have those permissions, it says homebrew cannot install anything and that you should change the permissions as specified. it's never affected my sophos install. also, brew prune removes broken symlinks that point to removed packages and brew cleanup removes outdated packages that have been replaced by newer ones. they don't remove any essential system files.

**Comment by bobthecow** [comment]
Yeah, I'm sure about all of those (potential) issues :)

As I said, these are things that _can_ complicate things, not that necessarily do. If none of them affect you, great. We just can't ship code that does destructive things to other peoples machines _assuming_ that they won't have any of these issues.
